name: JonAmazingPluginChangeNameLaterTestThingy
version: '1.0-SNAPSHOT'
main: space.vestiges.plugin1.adapterlayer.Plugin1
api-version: '1.21'
softdepend: [MythicMobs]
depend: [ProtocolLib]

commands:
  p:
    description: Test player stats commands
    usage: /p <action>