name: JonAmazingPluginChangeNameLaterTestThingy
version: '1.0-SNAPSHOT'
main: space.vestiges.plugin1.Plugin1
api-version: '1.21'

commands:
  p:
    description: Test player stats commands
    usage: /p <action>